### ISSUE TITLE
Datos de un usuario en concreto

### ISSUE THREAD

**Issue by xzebra** [adoptadiCOs/backend#28]
Solo se puede obtener lista de usuarios, necesitamos datos de un usuario.

**Comment by jmarindiez** [comment]
¿Datos del perfil (biografia, avatar, nombre de usuario, email, etc? ¿O relacionados con el foro (publicaciones, posts, etc)?

**Comment by xzebra** [comment]
Queremos poder obtener nombre, foto, biografía etc de un solo usuario

**Comment by xzebra** [comment]
La única manera ahora es con la lista entera de usuarios, pero si se accede al perfil es un overkill eso
